# -*- coding: utf-8 -*-
"""Normalization 29/2..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13dj0IdiYQt2IenhBqePbEqI5gMmgYyob
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/2,1 dataset titanic.csv")
df.head()

cols=['Name','Ticket','Cabin']
df=df.drop(cols,axis=1)
df.info()

df=df.dropna()
df.info()

dummies=[]
cols=['Pclass','Sex','Embarked']
for col in cols:
  dummies.append(pd.get_dummies(df[col]))

titanic_dummies=pd.concat(dummies,axis=1)

df=pd.concat((df,titanic_dummies),axis=1)

df=df.drop(['Pclass','Sex','Embarked'],axis=1)

df['Age']=df['Age'].interpolate()
print(df)

"""min max scaler and standard"""

from sklearn.preprocessing import MinMaxScaler
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
scaler=MinMaxScaler()
print(scaler.fit(data))
MinMaxScaler()
print(scaler.data_max_)
print(scaler.transform(data))

from numpy import asarray
from sklearn.preprocessing import StandardScaler
#define data
data=asarray([[100,0.001],[8,0.05],[50,0.005],[88,0.07],[4,0.1]])
print(data)
#define standard scaler
scaler=StandardScaler()
#transform data
scaled=scaler.fit_transform(data)
print(scaled)