# -*- coding: utf-8 -*-
"""Pandas series 8/2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lQgRbsml9dblKZ0K7_uaH4aoVkKW9jCp
"""

#import the pandas library and aliasing  as pd
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)

import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data,index=[100,101,102,103])
print(s)

"""if index is passed ,the values in data corresponding to the labels in the index will be pulled out"""

import pandas as pd
import numpy as np
data={'a':0.,'b':1.,'c':2.}
s=pd.Series(data)
print(s)

"""defining missing values"""

import pandas as pd
import numpy as np
data={'a':0.,'b':1.,'c':2.}
s=pd.Series(data,index=['b','c','d','a'])
print(s)

import pandas as pd
import numpy as np
s=pd.Series(5,index=[0,1,2,3])
print(s)

"""first element is stored at zeroth position and so on"""

import pandas as pd
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
#retrive a single element
print(s['a'])

import pandas as pd
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
#retrive a multiple elements
print(s[['a','c','e']])

import pandas as pd
df=pd.DataFrame()
print(df)

import pandas as pd
data=[['alex',10],['bob',11],['can',12]]
df=pd.DataFrame(data,columns=['Name','Age'])
print (df)

import pandas as pd
data=[['alex',10],['bob',11],['can',12]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print (df)

import pandas as pd
data ={'Name':['tom','jeery'],'age':[21,22]}
df=pd.DataFrame(data,index=['rank1','rank2'])
print(df)

"""create a dataframe from lists"""

import pandas as pd
data=[1,2,3,4,5]
df=pd.DataFrame(data)
print(df)

"""assigning columns"""

import pandas as pd
data=[['alex',10],['bob',12],['clarke',13]]
df=pd.DataFrame(data,columns=['name','age'],dtype='float')
print(df)

"""length of the index should be eqyal to the length of the arrays
if no index is passed then by default index will be range(n)where n is the array length
"""

import pandas as pd
data={'name':['tom','jack'],'age':[23,25]}
df=pd.DataFrame(data)
print(df)

"""list of dictionaries"""

import pandas as pd
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data)
print(df)

import pandas as pd
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
#with 2 column indices, values same as dictionary keys
df1=pd.DataFrame(data,index=['first','second'],columns=['a','b'])
df2=pd.DataFrame(data,index=['first','second'],columns=['a','b1'])
print(df1)
print(df2)

import pandas as  pd
d={'one':pd.Series([1,2,3],index=['a','b','c'])}
df=print
print